name: CI

on:
  pull_request:

jobs:
  protected-files:
    uses: blanck1945/boogiepop-platform-guards/.github/workflows/protected-files.yml@main
    secrets:
      PLATFORM_OWNER_USERNAME: ${{ secrets.PLATFORM_OWNER_USERNAME }}
